// Required-field table: which fields the grammar makes mandatory.
//
// The proto schema cannot carry this — compiler.Compile peels [ ] optionals
// and { } repetitions into plain (proto3-optional) fields, so a mandatory
// "{" keyword field and an optional "!important" marker look identical in
// the descriptor. The OnField hook sees the grammar node *before* peeling,
// which is where requiredness still exists. The codec's parser uses the
// table to fail a message whose required field doesn't match, instead of
// silently skipping it (which let degenerate alternatives win longest-match).
package main

import (
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/accretional/gluon/v2/compiler"
	pb "github.com/accretional/gluon/v2/pb"
)

// nodeRequired reports whether the grammar node that produced a field is
// mandatory. It mirrors compiler.emitField's peel loop: groups are
// transparent; an optional or repetition wrapper anywhere above the atom
// means the field may be absent.
func nodeRequired(node *pb.ASTNode) bool {
	for node != nil {
		switch node.GetKind() {
		case compiler.KindOptional, compiler.KindRepetition:
			return false
		case compiler.KindGroup:
			if len(node.GetChildren()) == 0 {
				return false
			}
			node = node.GetChildren()[0]
		default:
			return true
		}
	}
	return false
}

// filterRequired keeps only candidate keys that survived the fdp post-passes
// (dedupe, dangling-drop, uniquify, seam externalization) as plain singular
// non-oneof fields. Oneof alternatives are never required (the alternation
// chooses among them) and repeated fields match zero-or-more by construction.
func filterRequired(fdp *descriptorpb.FileDescriptorProto, pkg string, cand map[string]bool) map[string]bool {
	out := map[string]bool{}
	var walk func(m *descriptorpb.DescriptorProto, fqn string)
	walk = func(m *descriptorpb.DescriptorProto, fqn string) {
		for _, f := range m.GetField() {
			if f.OneofIndex != nil || f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
				continue
			}
			if key := fqn + "." + f.GetName(); cand[key] {
				out[key] = true
			}
		}
		for _, n := range m.GetNestedType() {
			walk(n, fqn+"."+n.GetName())
		}
	}
	for _, m := range fdp.GetMessageType() {
		walk(m, "."+pkg+"."+m.GetName())
	}
	return out
}

func formatRequiredMap(goPkgName string, required map[string]bool) string {
	keys := make([]string, 0, len(required))
	for k := range required {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by genproto. DO NOT EDIT.\n\n")
	b.WriteString("package " + goPkgName + "\n\n")
	b.WriteString("// FieldRequired maps a \"parentFQN.fieldName\" key to true when the grammar\n")
	b.WriteString("// makes that field mandatory (not [ ]-optional, not a repetition, not a\n")
	b.WriteString("// oneof alternative). The parser fails the containing message when a\n")
	b.WriteString("// required field fails to match.\n")
	b.WriteString("var FieldRequired = map[string]bool{\n")
	for _, k := range keys {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(k))
		b.WriteString(": true,\n")
	}
	b.WriteString("}\n")
	return b.String()
}
