// Scalar stop-chars: the lexical boundary scalarization erases, recovered.
//
// scalarizeLeaves collapses a leaf rule's range/terminal structure into a bare
// `string value = 1`, so the parser loses what characters the token may
// contain — an ident happily swallows ":;{}" and a custom element name
// swallows quotes and spaces. leafStopChars re-derives, per leaf rule, the
// printable ASCII characters the rule can NEVER match (the complement of the
// union of its ranges and terminal characters, nonterminals resolved). The
// codec cuts a scalar capture before the first such character, restoring the
// token boundary without needing a real lexer.
//
// Conservative by construction: any unresolvable or already-scalarized part
// of a rule makes its character set unbounded and the rule emits no stops
// (old swallow-to-stop-token behavior). Control characters are never emitted
// as stops so multi-line text keeps working.
package main

import (
	"sort"
	"strconv"
	"strings"

	"github.com/accretional/gluon/v2/compiler"
	pb "github.com/accretional/gluon/v2/pb"
)

// leafStopChars returns, for every rule that scalarizeLeaves will collapse,
// the set of printable ASCII characters the rule's grammar can never contain,
// keyed by rule name (mapped to message FQNs via the compile OnMessage hook).
// Rules whose character set is unbounded are omitted.
func leafStopChars(root *pb.ASTNode) map[string]string {
	rules := map[string]*pb.ASTNode{}
	for _, r := range root.GetChildren() {
		if r.GetKind() == compiler.KindRule {
			if _, ok := rules[r.GetValue()]; !ok {
				rules[r.GetValue()] = r
			}
		}
	}
	out := map[string]string{}
	for name, r := range rules {
		if !(leafTypes[norm(name)] || hasRange(r)) {
			continue
		}
		set := make([]bool, 128)
		if !charUnion(r, rules, map[string]bool{name: true}, set) {
			continue // unbounded — no lexical boundary derivable
		}
		var excluded []byte
		for c := byte(0x20); c < 0x7f; c++ {
			if !set[c] {
				excluded = append(excluded, c)
			}
		}
		if len(excluded) > 0 {
			out[name] = string(excluded)
		}
	}
	return out
}

// charUnion accumulates into set every printable ASCII character node can
// match, resolving nonterminals through rules (cycles contribute nothing new).
// Returns false when the set is unbounded: an unknown rule reference or an
// already-scalarized part means anything could appear.
func charUnion(node *pb.ASTNode, rules map[string]*pb.ASTNode, seen map[string]bool, set []bool) bool {
	if node == nil {
		return true
	}
	switch node.GetKind() {
	case compiler.KindScalar:
		return false
	case compiler.KindTerminal:
		for _, b := range []byte(node.GetValue()) {
			if b >= 0x20 && b < 0x7f {
				set[b] = true
			}
		}
		return true
	case compiler.KindRange:
		kids := node.GetChildren()
		if len(kids) != 2 {
			return false
		}
		lo, hi := firstRune(kids[0].GetValue()), firstRune(kids[1].GetValue())
		if lo < 0 || hi < 0 {
			return false
		}
		for c := max(lo, 0x20); c <= min(hi, 0x7e); c++ {
			set[c] = true
		}
		return true
	case compiler.KindNonterminal:
		name := node.GetValue()
		if seen[name] {
			return true // cycle: no new characters on revisit
		}
		r, ok := rules[name]
		if !ok {
			return false // dangling reference — unbounded
		}
		seen[name] = true
		return charUnion(r, rules, seen, set)
	default:
		for _, c := range node.GetChildren() {
			if !charUnion(c, rules, seen, set) {
				return false
			}
		}
		return true
	}
}

func firstRune(s string) rune {
	for _, r := range s {
		return r
	}
	return -1
}

func formatScalarStopsMap(goPkgName string, stops map[string]string) string {
	keys := make([]string, 0, len(stops))
	for k := range stops {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by genproto. DO NOT EDIT.\n\n")
	b.WriteString("package " + goPkgName + "\n\n")
	b.WriteString("// ScalarStopChars maps a scalarized leaf message's FQN to the printable\n")
	b.WriteString("// ASCII characters its grammar rule can never contain. The parser cuts a\n")
	b.WriteString("// scalar capture before the first such character — the lexical boundary\n")
	b.WriteString("// that collapsing the rule to `string value = 1` erased.\n")
	b.WriteString("var ScalarStopChars = map[string]string{\n")
	for _, k := range keys {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(k))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(stops[k]))
		b.WriteString(",\n")
	}
	b.WriteString("}\n")
	return b.String()
}
