// Code generated by genproto. DO NOT EDIT.

package svgpb

// ScalarStopChars maps a scalarized leaf message's FQN to the printable
// ASCII characters its grammar rule can never contain. The parser cuts a
// scalar capture before the first such character — the lexical boundary
// that collapsing the rule to `string value = 1` erased.
var ScalarStopChars = map[string]string{
	".svg.AlphaValue": " !\"#$&'()*+,-/:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".svg.AngleType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPQRSTUVWXYZ[\\]^_`bcfhijklmopqsvwxyz{|}~",
	".svg.Bcp47type": " !\"#$%&'()*+,/:;<=>?@[\\]^`{|}~",
	".svg.CharType": "\"",
	".svg.CharacterDataType": "<",
	".svg.CustomIdentType": " !\"#$%&'()*+,/:;<=>?@[\\]^`{|}~",
	".svg.EventSymbolType": " !\"#$%&'()*+,/:;<=>?@[\\]^`{|}~",
	".svg.FunctionalColor": " ",
	".svg.HexColor": " !\"$%&'()*+,-./:;<=>?@GHIJKLMNOPQRSTUVWXYZ[\\]^_`ghijklmnopqrstuvwxyz{|}~",
	".svg.IntegerType": " !\"#$%&'()*,./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".svg.IriType": " \"",
	".svg.LengthPercentageType": " !\"#$&'()*,/:;<=>?@ABCDFGHIJKLMNOPRSTUVWXYZ[\\]^_`bdfgjkloqsuyz{|}~",
	".svg.LengthType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPRSTUVWXYZ[\\]^_`bdfgjkloqsuyz{|}~",
	".svg.MiterLimitType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".svg.NonNegativeIntegerType": " !\"#$%&'()*+,-./:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
	".svg.NonNegativeLengthPercentageType": " !\"#$&'()*,/:;<=>?@ABCDFGHIJKLMNOPRSTUVWXYZ[\\]^_`bdfgjkloqsuyz{|}~",
	".svg.NonNegativeLengthType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPRSTUVWXYZ[\\]^_`bdfgjkloqsuyz{|}~",
	".svg.NonNegativeNumberType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".svg.NumberType": " !\"#$%&'()*,/:;<=>?@ABCDFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".svg.PercentageType": " !\"#$&'()*,/:;<=>?@ABCDFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdfghijklmnopqrstuvwxyz{|}~",
	".svg.StringType": "\"",
	".svg.UrlContentChar": " \"()",
	".svg.XmlNameType": " !\"#$%&'()*+,/:;<=>?@[\\]^`{|}~",
}
