// Code generated by genproto. DO NOT EDIT.

package svgpb

// SeamType maps a ".pkg.Message.field" key to the fully-qualified
// message type the field's google.protobuf.Any seam embeds (e.g.
// "css.CssStyleSheet"). The codec reads it to know what grammar to parse a
// seam's text as; the render direction reads the Any's own type_url.
var SeamType = map[string]string{
	".svg.AnimationValue.color_type": "css.ColorType",
	".svg.ColorAttr.color_type": "css.ColorType",
	".svg.DropShadowFunction.color_type": "css.ColorType",
	".svg.FloodColorAttr.Alt1.color_type": "css.ColorType",
	".svg.LightingColorAttr.Alt1.color_type": "css.ColorType",
	".svg.PaintFallback.color_type": "css.ColorType",
	".svg.PaintType.color_type": "css.ColorType",
	".svg.StopColorAttr.Alt1.color_type": "css.ColorType",
	".svg.SvgstyleElement.css_style_sheet": "css.CssStyleSheet",
	".svg.TextDecorationValue.Seq2.color_type": "css.ColorType",
	".svg.TextDecorationValue.Seq3.color_type": "css.ColorType",
	".svg.TextDecorationValue.Seq4.color_type": "css.ColorType",
}
