// Code generated by genproto. DO NOT EDIT.

package svgpb

// FieldSeparator maps a "parentFQN.fieldName" key to the literal that
// CollapseCommaList dropped when it rewrote "X (SEP X)*" into a repeated
// field. The renderer interleaves it between elements; the parser splits on it.
var FieldSeparator = map[string]string{
	".svg.AnimateTransformValues.animate_transform_single_value": ";",
	".svg.AnimationValueList.animation_value": ";",
	".svg.BeginValueList.begin_value": ";",
	".svg.EndValueList.end_value": ";",
	".svg.KeyPointsList.number_type": ";",
	".svg.KeySplinesList.control_point_set": ";",
	".svg.KeyTimesList.number_type": ";",
	".svg.MaskLayerList.mask_layer": " , ",
	".svg.MotionValues.motion_coordinate_pair": ";",
	".svg.PolygonFn.polygon_vertex": ",",
	".svg.ShapeFn.shape_command": ",",
}
