#!/usr/bin/env bash
# fetch_specs.sh — Download every W3C SVG specification document needed to author
# the SVG grammar, plus the companion specs (filters, masking, SMIL animation),
# and render each to readable plain text for manual reading.
#
# Output:
#   docs/specs/cache/<name>.html   raw spec HTML (source of record)
#   docs/specs/cache/<name>.txt    readable text (headings + verbatim <pre> BNF)
#   docs/specs/cache/INDEX.md      name -> URL -> local files map
#
# Idempotent: an existing non-empty <name>.html is reused unless FORCE=1 is set.
# The .txt is always (re)generated from the .html so converter fixes propagate.
#
#   FORCE=1 ./scripts/fetch_specs.sh   # re-download everything

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CACHE="$ROOT/docs/specs/cache"
CONV="$ROOT/scripts/html_to_text.py"
mkdir -p "$CACHE"

# name|url  — one document per line. SVG 2 core is one HTML page per chapter.
SPECS=(
  # ── SVG 2 core (https://www.w3.org/TR/SVG2/) ──────────────────────────────
  "svg2-intro|https://www.w3.org/TR/SVG2/intro.html"
  "svg2-conform|https://www.w3.org/TR/SVG2/conform.html"
  "svg2-render|https://www.w3.org/TR/SVG2/render.html"
  "svg2-types|https://www.w3.org/TR/SVG2/types.html"
  "svg2-struct|https://www.w3.org/TR/SVG2/struct.html"
  "svg2-styling|https://www.w3.org/TR/SVG2/styling.html"
  "svg2-geometry|https://www.w3.org/TR/SVG2/geometry.html"
  "svg2-coords|https://www.w3.org/TR/SVG2/coords.html"
  "svg2-paths|https://www.w3.org/TR/SVG2/paths.html"
  "svg2-shapes|https://www.w3.org/TR/SVG2/shapes.html"
  "svg2-text|https://www.w3.org/TR/SVG2/text.html"
  "svg2-embedded|https://www.w3.org/TR/SVG2/embedded.html"
  "svg2-painting|https://www.w3.org/TR/SVG2/painting.html"
  "svg2-pservers|https://www.w3.org/TR/SVG2/pservers.html"
  "svg2-interact|https://www.w3.org/TR/SVG2/interact.html"
  "svg2-linking|https://www.w3.org/TR/SVG2/linking.html"
  "svg2-implnote|https://www.w3.org/TR/SVG2/implnote.html"
  "svg2-changes|https://www.w3.org/TR/SVG2/changes.html"
  # SVG 2 completeness indices (authoritative name lists)
  "svg2-eltindex|https://www.w3.org/TR/SVG2/eltindex.html"
  "svg2-attindex|https://www.w3.org/TR/SVG2/attindex.html"
  "svg2-propidx|https://www.w3.org/TR/SVG2/propidx.html"

  # ── Companion specs (not in SVG 2 core) ──────────────────────────────────
  "filter-effects-1|https://www.w3.org/TR/filter-effects-1/"
  "css-masking-1|https://www.w3.org/TR/css-masking-1/"
  # Declarative animation: SVG 2 defers to SMIL. Pull all three sources.
  "svg11-animate|https://www.w3.org/TR/SVG11/animate.html"
  "svgwg-animations|https://svgwg.org/specs/animations/"
  "smil-animation|https://www.w3.org/TR/smil-animation/"
)

UA="Mozilla/5.0 (proto-svg grammar fetch; +https://www.w3.org/TR/SVG2/)"

fetched=0
reused=0
failed=0

echo "========================================="
echo "  fetch_specs.sh — download SVG specs"
echo "========================================="
echo "  cache: $CACHE"
echo ""

for entry in "${SPECS[@]}"; do
  name="${entry%%|*}"
  url="${entry#*|}"
  html="$CACHE/$name.html"
  txt="$CACHE/$name.txt"

  if [[ -s "$html" && -z "${FORCE:-}" ]]; then
    echo "  [reuse] $name  ($(wc -c <"$html" | tr -d ' ') bytes)"
    reused=$((reused + 1))
  else
    echo "  [fetch] $name  <- $url"
    if curl -fsSL --retry 3 --retry-delay 2 -A "$UA" "$url" -o "$html"; then
      fetched=$((fetched + 1))
    else
      echo "    [FAIL] could not download $url" >&2
      failed=$((failed + 1))
      continue
    fi
  fi

  # Always (re)generate the readable text from the cached HTML.
  if python3 "$CONV" "$html" "$txt"; then
    :
  else
    echo "    [warn] text conversion failed for $name" >&2
  fi
done

# ── Write an index mapping name -> url -> files ──────────────────────────────
{
  echo "# SVG spec cache index"
  echo ""
  echo "Generated by scripts/fetch_specs.sh. Read the .txt files (no grep) to author the grammar."
  echo ""
  echo "| name | source | text | html |"
  echo "| --- | --- | --- | --- |"
  for entry in "${SPECS[@]}"; do
    name="${entry%%|*}"
    url="${entry#*|}"
    echo "| $name | $url | cache/$name.txt | cache/$name.html |"
  done
} >"$CACHE/INDEX.md"

echo ""
echo "========================================="
echo "  fetched=$fetched reused=$reused failed=$failed"
echo "  index: $CACHE/INDEX.md"
echo "========================================="

[[ $failed -eq 0 ]]
