// Code generated by gluon servicegen (run via genproto). DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: svg_service.proto

package svgservicepb

import (
	svg "github.com/accretional/proto-svg/proto/pb/svg"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The SvgDocument to render. Any svg.* subtree is reachable from here.
	Document *svg.SvgDocument `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// Alternative root: an arbitrary grammar subtree packed as Any (as
	// returned in ParseResponse.node). Takes precedence over `document`.
	Node          *anypb.Any `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_svg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_svg_service_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetDocument() *svg.SvgDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *RenderRequest) GetNode() *anypb.Any {
	if x != nil {
		return x.Node
	}
	return nil
}

type RenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rendered SVG text.
	Svg           string `protobuf:"bytes,1,opt,name=svg,proto3" json:"svg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_svg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_svg_service_proto_rawDescGZIP(), []int{1}
}

func (x *RenderResponse) GetSvg() string {
	if x != nil {
		return x.Svg
	}
	return ""
}

type RenderChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A slice of the rendered SVG text. Concatenate chunks in arrival order.
	Svg           string `protobuf:"bytes,1,opt,name=svg,proto3" json:"svg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderChunk) Reset() {
	*x = RenderChunk{}
	mi := &file_svg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChunk) ProtoMessage() {}

func (x *RenderChunk) ProtoReflect() protoreflect.Message {
	mi := &file_svg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChunk.ProtoReflect.Descriptor instead.
func (*RenderChunk) Descriptor() ([]byte, []int) {
	return file_svg_service_proto_rawDescGZIP(), []int{2}
}

func (x *RenderChunk) GetSvg() string {
	if x != nil {
		return x.Svg
	}
	return ""
}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The SVG text to parse.
	Svg string `protobuf:"bytes,1,opt,name=svg,proto3" json:"svg,omitempty"`
	// Optional fully-qualified message type to parse as (e.g. a single
	// element or value production) instead of the SvgDocument root. The result
	// comes back Any-packed in ParseResponse.node.
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_svg_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svg_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_svg_service_proto_rawDescGZIP(), []int{3}
}

func (x *ParseRequest) GetSvg() string {
	if x != nil {
		return x.Svg
	}
	return ""
}

func (x *ParseRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ParseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parsed SvgDocument (set when ParseRequest.type was empty).
	Document *svg.SvgDocument `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// The parsed subtree, Any-packed (set when ParseRequest.type named a
	// non-root message).
	Node          *anypb.Any `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_svg_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svg_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_svg_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetDocument() *svg.SvgDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ParseResponse) GetNode() *anypb.Any {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_svg_service_proto protoreflect.FileDescriptor

const file_svg_service_proto_rawDesc = "" +
	"\n" +
	"\x11svg_service.proto\x12\x03svg\x1a\tsvg.proto\x1a\x19google/protobuf/any.proto\"g\n" +
	"\rRenderRequest\x12,\n" +
	"\bdocument\x18\x01 \x01(\v2\x10.svg.SvgDocumentR\bdocument\x12(\n" +
	"\x04node\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04node\"\"\n" +
	"\x0eRenderResponse\x12\x10\n" +
	"\x03svg\x18\x01 \x01(\tR\x03svg\"\x1f\n" +
	"\vRenderChunk\x12\x10\n" +
	"\x03svg\x18\x01 \x01(\tR\x03svg\"4\n" +
	"\fParseRequest\x12\x10\n" +
	"\x03svg\x18\x01 \x01(\tR\x03svg\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"g\n" +
	"\rParseResponse\x12,\n" +
	"\bdocument\x18\x01 \x01(\v2\x10.svg.SvgDocumentR\bdocument\x12(\n" +
	"\x04node\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04node2\xa7\x01\n" +
	"\n" +
	"SvgService\x121\n" +
	"\x06Render\x12\x12.svg.RenderRequest\x1a\x13.svg.RenderResponse\x126\n" +
	"\fRenderStream\x12\x12.svg.RenderRequest\x1a\x10.svg.RenderChunk0\x01\x12.\n" +
	"\x05Parse\x12\x11.svg.ParseRequest\x1a\x12.svg.ParseResponseBCZAgithub.com/accretional/proto-svg/proto/pb/svgservice;svgservicepbb\x06proto3"

var (
	file_svg_service_proto_rawDescOnce sync.Once
	file_svg_service_proto_rawDescData []byte
)

func file_svg_service_proto_rawDescGZIP() []byte {
	file_svg_service_proto_rawDescOnce.Do(func() {
		file_svg_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svg_service_proto_rawDesc), len(file_svg_service_proto_rawDesc)))
	})
	return file_svg_service_proto_rawDescData
}

var file_svg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_svg_service_proto_goTypes = []any{
	(*RenderRequest)(nil),   // 0: svg.RenderRequest
	(*RenderResponse)(nil),  // 1: svg.RenderResponse
	(*RenderChunk)(nil),     // 2: svg.RenderChunk
	(*ParseRequest)(nil),    // 3: svg.ParseRequest
	(*ParseResponse)(nil),   // 4: svg.ParseResponse
	(*svg.SvgDocument)(nil), // 5: svg.SvgDocument
	(*anypb.Any)(nil),       // 6: google.protobuf.Any
}
var file_svg_service_proto_depIdxs = []int32{
	5, // 0: svg.RenderRequest.document:type_name -> svg.SvgDocument
	6, // 1: svg.RenderRequest.node:type_name -> google.protobuf.Any
	5, // 2: svg.ParseResponse.document:type_name -> svg.SvgDocument
	6, // 3: svg.ParseResponse.node:type_name -> google.protobuf.Any
	0, // 4: svg.SvgService.Render:input_type -> svg.RenderRequest
	0, // 5: svg.SvgService.RenderStream:input_type -> svg.RenderRequest
	3, // 6: svg.SvgService.Parse:input_type -> svg.ParseRequest
	1, // 7: svg.SvgService.Render:output_type -> svg.RenderResponse
	2, // 8: svg.SvgService.RenderStream:output_type -> svg.RenderChunk
	4, // 9: svg.SvgService.Parse:output_type -> svg.ParseResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_svg_service_proto_init() }
func file_svg_service_proto_init() {
	if File_svg_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svg_service_proto_rawDesc), len(file_svg_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svg_service_proto_goTypes,
		DependencyIndexes: file_svg_service_proto_depIdxs,
		MessageInfos:      file_svg_service_proto_msgTypes,
	}.Build()
	File_svg_service_proto = out.File
	file_svg_service_proto_goTypes = nil
	file_svg_service_proto_depIdxs = nil
}
