// Code generated by gluon servicegen (run via genproto). DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: svg_service.proto

package svgservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SvgService_Render_FullMethodName       = "/svg.SvgService/Render"
	SvgService_RenderStream_FullMethodName = "/svg.SvgService/RenderStream"
	SvgService_Parse_FullMethodName        = "/svg.SvgService/Parse"
)

// SvgServiceClient is the client API for SvgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SvgService renders typed SvgDocument messages to SVG text and parses SVG text
// back. SvgDocument is the grammar's start symbol — every svg.* message is
// reachable from it — so both directions are rooted there. Both directions are
// pure reflection over the grammar-derived schema in svg.proto plus the generated
// tables; the gluon codec does all parsing and rendering, so the implementing
// server carries no per-rule logic.
type SvgServiceClient interface {
	// Render serializes the request's SvgDocument into SVG text.
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// RenderStream serializes the request's SvgDocument and streams the SVG text
	// in chunks. The concatenation of all chunks equals Render's `svg`.
	RenderStream(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RenderChunk], error)
	// Parse parses SVG text into a typed SvgDocument.
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type svgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSvgServiceClient(cc grpc.ClientConnInterface) SvgServiceClient {
	return &svgServiceClient{cc}
}

func (c *svgServiceClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, SvgService_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svgServiceClient) RenderStream(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RenderChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SvgService_ServiceDesc.Streams[0], SvgService_RenderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderRequest, RenderChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SvgService_RenderStreamClient = grpc.ServerStreamingClient[RenderChunk]

func (c *svgServiceClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, SvgService_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SvgServiceServer is the server API for SvgService service.
// All implementations must embed UnimplementedSvgServiceServer
// for forward compatibility.
//
// SvgService renders typed SvgDocument messages to SVG text and parses SVG text
// back. SvgDocument is the grammar's start symbol — every svg.* message is
// reachable from it — so both directions are rooted there. Both directions are
// pure reflection over the grammar-derived schema in svg.proto plus the generated
// tables; the gluon codec does all parsing and rendering, so the implementing
// server carries no per-rule logic.
type SvgServiceServer interface {
	// Render serializes the request's SvgDocument into SVG text.
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	// RenderStream serializes the request's SvgDocument and streams the SVG text
	// in chunks. The concatenation of all chunks equals Render's `svg`.
	RenderStream(*RenderRequest, grpc.ServerStreamingServer[RenderChunk]) error
	// Parse parses SVG text into a typed SvgDocument.
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedSvgServiceServer()
}

// UnimplementedSvgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSvgServiceServer struct{}

func (UnimplementedSvgServiceServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedSvgServiceServer) RenderStream(*RenderRequest, grpc.ServerStreamingServer[RenderChunk]) error {
	return status.Error(codes.Unimplemented, "method RenderStream not implemented")
}
func (UnimplementedSvgServiceServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedSvgServiceServer) mustEmbedUnimplementedSvgServiceServer() {}
func (UnimplementedSvgServiceServer) testEmbeddedByValue()                    {}

// UnsafeSvgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SvgServiceServer will
// result in compilation errors.
type UnsafeSvgServiceServer interface {
	mustEmbedUnimplementedSvgServiceServer()
}

func RegisterSvgServiceServer(s grpc.ServiceRegistrar, srv SvgServiceServer) {
	// If the following call panics, it indicates UnimplementedSvgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SvgService_ServiceDesc, srv)
}

func _SvgService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvgServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SvgService_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvgServiceServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SvgService_RenderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RenderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SvgServiceServer).RenderStream(m, &grpc.GenericServerStream[RenderRequest, RenderChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SvgService_RenderStreamServer = grpc.ServerStreamingServer[RenderChunk]

func _SvgService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvgServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SvgService_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvgServiceServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SvgService_ServiceDesc is the grpc.ServiceDesc for SvgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SvgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svg.SvgService",
	HandlerType: (*SvgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _SvgService_Render_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _SvgService_Parse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RenderStream",
			Handler:       _SvgService_RenderStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "svg_service.proto",
}
